name: ptint
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bottom_navy_bar: null
  carousel_slider: ^2.3.1
  cloud_firestore: ^0.14.1+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  cupertino_radio_choice: null
  dio: null
  direct_select: ^1.1.0
  dropbox_client: ^0.7.1
  ext_storage: ^1.0.3

  file_picker: ^2.0.8
  firebase_analytics: ^6.0.1
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0
  firebase_crashlytics: ^0.2.1
  firebase_database: null
  firebase_storage: null
  flutter_datetime_picker: ^1.4.0
  flutter_downloader: ^1.4.4

  flutter_full_pdf_viewer: ^1.0.6
  flutter_plugin_pdf_viewer: ^1.0.7
  flutter_secure_storage: ^3.2.1+1
  flutter_spinkit: ^4.1.2+1
  #flutter_full_pdf_viewer: ^1.0.6
  #path_provider: ^1.6.16
  #share: ^0.6.5+1
  flutter_swiper: ^1.1.6
  flutter_vector_icons: ^0.2.1

  fluttertoast: ^7.1.1

  font_awesome_flutter: ^8.10.0
  #google_map_location_picker: ^4.0.0
  #google_maps_flutter:
  geolocator: ^6.0.0+4
  giffy_dialog: ^1.8.0
  google_fonts: ^1.1.1
  google_map_location_picker: null
  google_maps_flutter: null
  googleapis: ^0.56.1
  ###
  googleapis_auth: any
  gscarousel: ^0.0.1

  http: ^0.12.0+4
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+12
  intl: ^0.16.1
  liquid_swipe: ^1.5.0
  #flutter_share: ^1.0.2+1
  #pdf: ^1.11.2
  motion_tab_bar: ^0.1.5
  open_file: ^3.0.3
  path: ^1.7.0
  #path_provider: ^1.6.24
  provider: ^4.3.3
  printing: null
  scoped_model: ^1.1.0
  searchable_dropdown: ^1.1.3
  shape_of_view: ^1.0.2

  sk_onboarding_screen: null
  sliding_sheet: ^0.4.1
  splashscreen: ^1.3.5

  url_launcher: ^5.7.0
  geocoder: ^0.2.1
  badges: ^1.1.6
  collection: ^1.14.13
  bloc:
  flutter_bloc:
  shared_preferences: ^0.5.12+4
  google_sign_in:
  animator: ^2.0.2


dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1


flutter_icons:
  ios: true
  image_path: "assets/icon/Untitled-3@60x60x1.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/icon/app@60x60x1.png
  #  assets:
  # - assets/ font/Janna LT Bold.ttf
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
